site_name: Dados Marlon
theme:
  name: 'material'
  palette:
      primary: 'teal'
      accent: 'blue'
  font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
  logo:
      icon: 'important_devices'
  language: 'pt'
  extra:
  search:
      language: 'en, pt'
  feature:
      tabs: true
repo_name: 'M4rlon-R0drigues'
repo_url: 'https://github.com/M4rlon-R0drigues'
google_analytics: ['UA-36723568-3', 'mkdocs.org']
extra:
  theme_inverse: false